name: Packing My Unreal Project

on: 
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
      group: ${{github.workflow}}-${{github.ref}}
      cancel-in-progress: true


jobs:
    build:
        runs-on: self-hosted
        name: Packing My Unreal Project
        steps: 
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Package Project
            env: 
                UE_PATH: ${{secrets.UE_PATH}}
                PROJECT_PATH:  ${{secrets.PROJECT_PATH}}
                OUTPUT_PATH: ${{secrets.OUTPUT_PATH}}
            run: |
             & $env:UE_PATH\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project="$env:PROJECT_PATH" -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development -cook -allmaps -build -stage -pak -archive -archivedirectory="$env:OUTPUT_PATH"


          - name: Upload Build Artifact
            uses: actions/upload-artifact@v4
            with: 
              name: UnrealBuild-${{github.sha}}
              path: ${{secrets.OUTPUT_PATH}}
              retention-days: 7
    upload:
          name: Upload to Google Drive
          needs: build
          runs-on: self-hosted
          steps:
            - name: Upload to Google drive
              env:
                OUTPUT_PATH: ${{secrets.OUTPUT_PATH}}
                RCLONE_PATH: ${{secrets.RCLONE_PATH}}
              run: |
                & "$env:RCLONE_PATH" copy "$env:OUTPUT_PATH" gdrive:UnrealBuilds/PG29CC --progress

              

