name: Packing My Unreal Project

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        name: Packing My Unreal Project
        steps: 
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Package Project
            env: 
                UE_PATH: 'C:\Program Files\Epic Games\UE_5.6'
                PROJECT_PATH: 'C:\Users\Tyler\Downloads\PG29CC\PG29CC\PG29CC.uproject'
                OUTPUT_PATH: 'C:\Users\Tyler\Documents\Builds'
            run: |
             & $env:UE_PATH\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project="$env:PROJECT_PATH" -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development -cook -allmaps -build -stage -pak -archive -archivedirectory="$env:OUTPUT_PATH"

          - name: Upload to Google Drive
            env:
                 OUTPUT_PATH: 'C:\Users\Tyler\Documents\Builds'
            run: |
             & "C:\Users\Tyler\AppData\Local\Microsoft\WinGet\Links\rclone.exe" copy "$env:OUTPUT_PATH" gdrive:UnrealBuilds/PG29CC --progress

                

